### ISSUE TITLE
Support generate keys from account extend public key.

### ISSUE THREAD

**Issue by zmrenwu** [kigawas/python-bip44#36]
Currencty, bip32 object is encapsulated in the `Wallet` class as a private property which could only instantiate from mnemonic. If we can provide some ways to allow client instantiate bip32 object from other source such as xpub, this can offer more flexibility to this library. How do you think? If you have the plan, I would be happy to work on it and submit a PR if I can.

**Comment by kigawas** [comment]
Good idea, but if you don't need the mnemonic, maybe python-bip32 would be more appropriate to your needs.
